// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Es ist extrem Wichtig diesen Code zu haben, weil aus diesem die Ordner Struktur 
  // erstellt wird, auf die in der docusaurus.config.js zugegriffen wird
  ap1Sidebar: [{type: 'autogenerated', dirName: '.'}],
  nutzerSidebar: [{type: 'autogenerated', dirName: 'Nutzer'}],
  
  // But you can create a sidebar manually
  
  /*tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['docs/category/tutorial---basics', 'Tutorial zu Docusaurus/tutorial-basics/create-a-blog-post'],
    },
  ],*/
};

export default sidebars;
